title: Route
tagline: "Route is a fast routing/dispatcher package enabling you to build well designed performant web apps."
description: "Route is a fast routing/dispatcher package enabling you to build well designed performant web apps."
google_analytics_tracking_id: UA-58477653-2
